apiVersion: v1
kind: Service
metadata:
  name: auto-provisioning-lb
  labels:
    app: dcos
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 30001
  selector:
    app: auto-provisioning-api